package com.example.features.recovery_engine.domain.entities

/**
 * Personalized recovery strategy dynamically generated by the Recovery Engine.
 */
data class RecoveryStrategy(
  val focus: String,
  val priorities: List<String>,
  val dailyExercises: List<String>,
  val personalizedTips: List<String>,
  val aiContextPrompt: String
)
